crosschain:
  network: testnet
  # Add overrides or new chains here.
  chains:
    ETH:
      chain: ETH
      driver: evm
      net: testnet
      url: "https://goerli.infura.io/v3"
      auth: "env:INFURA_API_TOKEN"
      provider: infura
      chain_id: 5
      chain_name: Ethereum (Goerli)
      explorer_url: "https://goerli.etherscan.io"
      decimals: 18
    MATIC:
      chain: MATIC
      driver: evm
      net: testnet
      url: "https://rpc-mumbai.matic.today"
      chain_id: 80001
      chain_name: Polygon (Mumbai)
      explorer_url: "https://mumbai.polygonscan.com"
      decimals: 18
      chain_max_gas_price: 100
    TRX:
      chain: TRX
      driver: tron
      net: testnet
      url: "https://nile.trongrid.io"
      chain_name: Nile
      explorer_url: "http://nile.tronscan.org"
      decimals: 6
      chain_max_gas_price: 200000000
  tokens:
    USDC.INJ:
      asset: USDC
      chain: INJ
      net: ""
      decimals: 18
      contract: peggy0x44C21afAaF20c270EBbF5914Cfc3b5022173FEB7
      type: "native"
    USDT.TRX:
      asset: USDT
      chain: TRX
      net: ""
      decimals: 6
      contract: TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj
